baseURL = "http://localhost:1313/nbfc26/"
#baseURL = "https://theochemui.github.io/nbfc26/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "16th NBFC, June 29 - July 1 2026, University of Iceland"
[Params]
  hometitle = "16th NORDIC BALTIC FEMTOCHEMISTRY CONFERENCE"
  # logo="img/ui_logo.png"
  subtitle = "June 29 - July 1 2026, University of Iceland"
[[Params.bigimg]]
  src = "img/reykjavik_panorama.jpg"
  desc = "NBFC 2026"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "NBFC2026"
   email = "giale@hi.is"
   github = "theochemui"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

#[[menu.main]]
#    name = "Program"
#    url = "planning"
#    weight = 2

# [[menu.main]]
#     name="Posters"
#     url = "posters"
#     weight = 3

#[[menu.main]]
#    name = "Location"
#    url = "map"
#    weight = 4

#[[menu.main]]
#    name = "Participants"
#    url = "participants"
#    weight = 5

[[menu.main]]
    name = "Venue"
    url = "venue"
    weight = 5

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 6

[[menu.main]]
    name = "Contacts"
    url = "contacts"
    weight = 7

