baseURL = "http://localhost:1313/nbfc26/"
#baseURL = "https://theochemui.github.io/nbfc26/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "16th NBFC, June 29 - July 1 2026, University of Iceland"
[Params]
  hometitle = "16th NORDIC BALTIC FEMTOCHEMISTRY CONFERENCE"
  # logo="img/ui_logo.png"
  subtitle = "June 29 - July 1 2026, University of Iceland"
  sponsorsTitle = "Sponsored by"

    [[Params.sponsors]]
    name = "UI"
    url  = "https://english.hi.is/"
    logo = "img/ui_logo_2.png"
    [[Params.sponsors]]
    name = "SENS"
    url  = "https://english.hi.is/about-ui/schools-and-faculties/school-engineering-and-natural-sciences"
    logo = "img/sens_logo_2.jpg"
    [[Params.sponsors]]
    name = "Light Conversion"
    url  = "https://lightcon.com/"
    logo = "img/LC_logo.png"

[[Params.bigimg]]
  src = "img/reykjavik_panorama.jpg"
  desc = "NBFC 2026"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "NBFC2026"
   email = "giale@hi.is"
   github = "theochemui"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Registration"
    url = "registration"
    weight = 2

[[menu.main]]
    name = "Abstract Submission"
    url = "abstract"
    weight = 3

[[menu.main]]
    name = "Program"
    url = "program"
    weight = 4

[[menu.main]]
    name = "Posters"
    url = "posters"
    weight = 5

[[menu.main]]
    name = "Venue"
    url = "venue"
    weight = 6

[[menu.main]]
    name = "Accommodation"
    url = "accommodation"
    weight = 7

[[menu.main]]
    name = "Sponsorship"
    url = "sponsors"
    weight = 8

[[menu.main]]
    name = "Contacts"
    url = "contacts"
    weight = 9
